import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { bdConnect } from "./services/mongo";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Noir Events",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  await bdConnect()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main className="py-24">
        {children}
        </main>
      </body>
    </html>
  );
}
